4.4 tidyup
ssbc/ssb-tribes2 pull request #121
Opened 2023-05-24 08:12 UTC by mixmix

2023-05-24 13:31 UTC, Powersource requested changes
approved except for small stuff

2023-05-26 00:51 UTC, mixmix commented on test/lib/epochs.test.js
>    // TODO need to test epochs > 2
done

2023-05-26 00:52 UTC, mixmix commented on test/lib/epochs.test.js
>    // TODO need to test epochs > 2
https://github.com/ssbc/ssb-tribes2/issues/125

2023-05-26 00:53 UTC, mixmix commented on test/lib/epochs.test.js
> +  //   - bob exlcudes carol, oscar
```suggestion
  //   - bob exlcudes oscar
```

2023-05-26 01:05 UTC, mixmix commented
added changes, rebased. merging

2023-05-26 01:05 UTC, merged