lib/epochs tieBreak
ssbc/ssb-tribes2 pull request #92
Opened 2023-04-14 01:42 UTC by mixmix

Feel free to merge

2023-04-14 18:20 UTC, Powersource requested changes

2023-04-14 18:20 UTC, Powersource commented on lib/epochs.js
> +        .sort()
https://github.com/ssbc/ssb-group-exclusion-spec#43-tie-breaking-rule


> The tie-breaking rule is: among the forked epochs, sort their epoch keys by lexicographic order (in hexadecimal encoding) and the epoch with the smallest epoch key is considered the winner.


Needs to be hex encoding not base64!

2023-04-18 22:06 UTC, mixmix commented on lib/epochs.js
> +        .map(epoch => epoch.epochKey.toString('base64'))
```suggestion
        .map(epoch => epoch.epochKey.toString('hex'))
```

2023-04-18 22:13 UTC, mixmix commented
updated, please review again and merge @Powersource

2023-04-20 01:56 UTC, merged